### ISSUE TITLE
docker issues. 

### ISSUE THREAD

**Issue by Salpertio** [idio-sync/romm-comm#10]

**Comment by Salpertio** [comment]
once again quick enter. 

so its been working great thus far until i updated to the latest. now i receive. 


`2024-11-23 21:05:30,180 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-23 21:05:42,496 - romm_bot - ERROR - Error starting bot:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 989, in _resolve_host
    return await asyncio.shield(resolved_host_task)
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/resolver.py", line 38, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 930, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 436, in main
    await bot.start(bot.config.TOKEN)
  File "/opt/venv/lib/python3.8/site-packages/discord/client.py", line 724, in start
    await self.login(token)
  File "/opt/venv/lib/python3.8/site-packages/discord/client.py", line 578, in login
    data = await self.http.static_login(token.strip())
  File "/opt/venv/lib/python3.8/site-packages/discord/http.py", line 421, in static_login
    data = await self.request(Route("GET", "/users/@me"))
  File "/opt/venv/lib/python3.8/site-packages/discord/http.py", line 286, in request
    async with self.__session.request(
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1360, in __aenter__
    self._resp: _RetType = await self._coro
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 538, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1341, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
2024-11-23 21:05:42,502 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x14dee5b00f10>`

im going to check locally by resetting the router and flushing dns but when i ping discord i receive replies...

**Comment by idio-sync** [comment]
Hmm yeah that looks like a regular old network error but I'll dig a bit and see if I can find anything that may cause this. Let me know if it clears up for you upon a router and bot restart.

**Comment by Salpertio** [comment]
it looks like docker got a bit clogged for whatever reason. a reboot fixed the issue. but good thing i took a look at the router (cve update) false alarm. have a great day.
